# Site settings 配置站点
title: '还是夸张一点技术专栏'
description: '一个专注于开发的普通技术民工。'
keyword: 'C# VB Vue 小程序'
url: 'https://18487115313.github.io' # your host

# if you don't need baseurl, you should leave this value blank.
baseurl: ''

# Navigation links
nav:
  首页: '/'
  博客内容: '/tags.html'

# Footer
footer:
  since: 2019

# Author 配置博主信息
author: '还是夸张一点'
nickname: '还是夸张一点'
bio: 'C# VB Vue 小程序'
avatar: '/assets/img/profile.png'

# Search
search: true

# Night mode
nightMode: false

# Comments 评论功能
comments:
  disqus: false
  disqus_url: 'https://liaokeyu.disqus.com/embed.js'

# MathJax 公式支持 by Ray-Eldath
mathjax: true

# Share
social-share: true
social-share-items: ['wechat', 'weibo', 'douban', 'twitter']

# theme color 主题皮肤
theme-color: 'default'  # pink or default

# Post header background patterns (when the post no cover): circuitBoard, overlappingCircles, food, glamorous, ticTacToe, seaOfClouds
postPatterns: 'circuitBoard'

# SNS settings 配置社交网站
# url: email, weibo, zhihu, twitter, instagram, juejin, github, douban, facebook, dribble, uicn, jianshu, medium, linkedin
sns:
  weibo: '//weibo.com/u/3915130057?is_all=1'
  # juejin: '//juejin.im/user/57a6f434165abd006159b4cc'
  # instagram: '//www.instagram.com/steveliaocn'
  github: '//github.com/18487115313'

# Tags 设置标签
recommend-tags: true # whether or not display recommend-tags on the sidebar
recommend-condition-size: 12 # a tag will be recommended if the size of it is more than this value
# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
baidu_tongji_id: 7d8d276a8d3670be19b0091a12eeed4a
# google_analytics_id: UA-72449510-4 # google 分析追踪id
# Build settings
paginate: 6
paginate_path: 'page:num'
exclude: ['node_modules', 'dev', 'package.json', 'gulpfile.js', '.gitignore', 'README.md']

# Markdown
markdown: kramdown
highlighter: Rouge
# highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: Rouge

# RSS
RSS: false

# Permalink
# See: https://github.com/kaeyleo/jekyll-theme-H2O/issues/35
permalink: /:year/:month/:day/:title.html
# excerpt
excerpt_separator: "\n\n\n\n"

# Plugins
# plugins: [jekyll-paginate]
# paginate: 6
# port: 4001
